# Generated by Django 5.1.7 on 2025-03-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AplicacionAgroquimico',
            new_name='Aplicacion',
        ),
    ]
