# Generated by Django 5.1.7 on 2025-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remito',
            name='total',
        ),
        migrations.AlterField(
            model_name='remito',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='remito',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
    ]
