# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_remove_remito_total_alter_remito_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_stock',
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
