# Generated by Django 5.1.7 on 2025-03-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='establecimientos.campo')),
            ],
        ),
    ]
